export const plans = {
  a: {
    id: "a",
    label: "Plan A",
    title: "High Masking Neurotypical Jobs",
    tagline: "Some suitable fundamental attributes but no disclosure and low accommodation potential.",
    color: "blue",
    accent: "#3b82f6",
    description: "",
    options: [
      {
        title: "Field Sampler",
        sector: "Environmental, Earth & Geosciences (Science & Technology)",
        background: "From Seek",
        summary: "ALS Water - Job advertisement - https://au.seek.com/job/92364393?ref=saved-homepage&pos=2&origin=jobTitle",
        whyIt: "Field based. Solo work, moderate autonomy. Mon - Thurs 7am to 3pm.",
        considerations: "Lots of city driving. Junior role. Sites are mostly industrial. Requires Negotiation and conflict resolution skills. Large organisation and associated social and structural norms.",
        timeToEntry: "Current advertisement",
        salaryRange: "Likely $40/hr",
        nextSteps: "Decide to apply or not.",
        reflections: "2026-06-19: Driving and client management not great nervous system match. 2026-06-22: Politics, social, team dynamics of large org make me shudder.",
      },
    ],
  },
  b: {
    id: "b",
    label: "Plan B",
    title: "Low Masking Neurotypical Jobs",
    tagline: "Jobs fit needs well, good accommodation potential, possible disclosure.",
    color: "emerald",
    accent: "#10b981",
    description: "",
    options: [
      {
        title: "Vessel Traffic Services (VTS) Officer",
        sector: "Spatial / Marine / Emergency Management",
        background: "Karlie said they are looking for peoplle with excellent spatial awaremenss and love to learn. Previously they have hired late career marine experts but have now realised the skill they need is spatial awareness and processing and that the marine content can be taught. Karlie said it sounds like he was describing her husband and the guy said does he want a job.",
        summary: "VTS Officer - https://www.linkedin.com/posts/ports-victoria_vessel-traffic-services-officer-casual-activity-7099984837112983552-Fkhp",
        whyIt: "Casual. Strong interest area with variety. Spatial skills highly relevant. Tasks and roles well defined. EM experience relevant. Transport experience adjacent (?). Is content focused, not relationship and influence dependent.",
        considerations: "Unknown culture, could be a bit blokey / old school. No physical movement. Unknown ND inclusion profile. Not sure how much of 'communicate and coordinate the day-to-day movement of vessels' is verbal / in-person, ideally most will be through spatial portal. Family logistics if same emergencies as Karlie.",
        timeToEntry: "Unknown",
        salaryRange: "Unknown",
        nextSteps: "Chat to Karlie to assess if it is a serious option. Contact Ports Vic guy to explore further. Ask if it would be possible to shadow for a shift to make sure.",
        reflections: "2026-06-19: Can sensory needs be met, a bit worried about a control room being noisy, bright and unable to move my body. 2026-06-22: Need to decide on disclosure, gut says not initially but simply state preferred and effective ways of working (?). 2026-06-22: Feels quite good, worth taking next steps, strongest positive driver is interest in the content, flexing the spatial skills, and cool new stuff to learn.",
      },
      {
        title: "GIS / Geospatial Analyst",
        sector: "Spatial / Environment / Government",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
      {
        title: "Online Data Analyst (Telus / Peroptyx)",
        sector: "Remote / Tech / Evaluation",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
    ],
  },
  c: {
    id: "c",
    label: "Plan C",
    title: "Unmasked Neurodiverse Jobs",
    tagline: "Full disclosure, primarily unmasked, high autonomy.",
    color: "violet",
    accent: "#8b5cf6",
    description: "",
    options: [
      {
        title: "Neurokindred Facilitator",
        sector: "Community / Neurodiversity / Education",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
      {
        title: "Neurodiversity Advocate / Coach",
        sector: "Education / Healthcare / Corporate",
        background: "Background to come.",
        summary:
          "Support neurodivergent individuals or organisations in understanding and embracing different ways of thinking and working.",
        whyIt: "Highly meaningful; lived experience is a genuine asset rather than a liability.",
        considerations: "Requires certification/training; emotionally demanding at times.",
        timeToEntry: "6–12 months",
        salaryRange: "£35k–£65k employed; higher self-employed",
        nextSteps: "Research coaching certifications, connect with neurodiversity orgs",
        reflections: "Reflections to come.",
      },
      {
        title: "Autistic Tour Guide",
        sector: "Tourism / Education / Culture",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
      {
        title: "Solopreneur / Niche Business Owner",
        sector: "Self-directed",
        background: "Background to come.",
        summary:
          "Build something small, intentional, and entirely yours. Could be a product, service, or community around a specific passion or skill.",
        whyIt: "Radical autonomy; work shaped entirely around your strengths and values.",
        considerations: "Highest risk, highest reward. Requires financial runway and resilience.",
        timeToEntry: "6–24 months",
        salaryRange: "Variable — loss to £200k+",
        nextSteps: "Validate idea with 10 people, build an audience before building a product",
        reflections: "Reflections to come.",
      },
    ],
  },
};

export const planOrder = ["a", "b", "c"];
