export const plans = {
  a: {
    id: "a",
    label: "Plan A",
    title: "High Masking Neurotypical Jobs",
    tagline: "Some suitable fundamental attributes but no disclosure and low accommodation potential.",
    color: "blue",
    accent: "#3b82f6",
    description: "",
    options: [
      {
        title: "Field Sampler",
        sector: "Environmental, Earth & Geosciences (Science & Technology)",
        background: "From Seek",
        summary: "ALS Water - Job advertisement - https://au.seek.com/job/92364393?ref=saved-homepage&pos=2&origin=jobTitle",
        whyIt: "Field based. Solo work, moderate autonomy. Mon - Thurs 7am to 3pm.",
        considerations: "Lots of city driving. Junior role. Sites are mostly industrial. Requires Negotiation and conflict resolution skills. Large organisation and associated social and structural norms.",
        timeToEntry: "Current advertisement",
        salaryRange: "Likely $40/hr",
        nextSteps: "Decide to apply or not.",
        reflections: "2026-06-19: Driving and client management not great nervous system match. 2026-06-22: Politics, social, team dynamics of large org make me shudder.",
      },
    ],
  },
  b: {
    id: "b",
    label: "Plan B",
    title: "Low Masking Neurotypical Jobs",
    tagline: "Jobs fit needs well, good accommodation potential, possible disclosure.",
    color: "emerald",
    accent: "#10b981",
    description: "",
    options: [
      {
        title: "Vessel Traffic Services (VTS) Officer",
        sector: "Spatial / Logistics / Emergency Management",
        background: "Background to come.",
        summary:
          "A great opportunity has arisen to join Ports Victoria as a casual Vessel Traffic Services (VTS) Officer. The positions (x2) are located at the Port Operations Control Centre (Lorimer Street, Port Melbourne). You will utilise modern technology to monitor, communicate and coordinate the day-to-day movement of vessels, whilst also providing a support function in emergency response arrangements.",
        whyIt: "Karlie said they are looking for peoplle with excellent spatail awaremenss and love to learn. Is in an interest area. Is a casual role.",
        considerations: "How much stakehoolder management is there, and can seensory needs be met. Is the communication of vessels verbal / in person or is it mostly tech based.",
        timeToEntry: "3–9 months",
        salaryRange: "Unknown",
        nextSteps: "Ideally ask if I can shadow a shift to make sure it is a good fit - discuss with Karlie",
        reflections: "Reflections to come.",
      },
      {
        title: "GIS / Geospatial Analyst",
        sector: "Spatial / Environment / Government",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
      {
        title: "Online Data Analyst (Telus / Peroptyx)",
        sector: "Remote / Tech / Evaluation",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
    ],
  },
  c: {
    id: "c",
    label: "Plan C",
    title: "Unmasked Neurodiverse Jobs",
    tagline: "Full disclosure, primarily unmasked, high autonomy.",
    color: "violet",
    accent: "#8b5cf6",
    description: "",
    options: [
      {
        title: "Neurokindred Facilitator",
        sector: "Community / Neurodiversity / Education",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
      {
        title: "Neurodiversity Advocate / Coach",
        sector: "Education / Healthcare / Corporate",
        background: "Background to come.",
        summary:
          "Support neurodivergent individuals or organisations in understanding and embracing different ways of thinking and working.",
        whyIt: "Highly meaningful; lived experience is a genuine asset rather than a liability.",
        considerations: "Requires certification/training; emotionally demanding at times.",
        timeToEntry: "6–12 months",
        salaryRange: "£35k–£65k employed; higher self-employed",
        nextSteps: "Research coaching certifications, connect with neurodiversity orgs",
        reflections: "Reflections to come.",
      },
      {
        title: "Autistic Tour Guide",
        sector: "Tourism / Education / Culture",
        background: "Background to come.",
        summary: "Details to come.",
        whyIt: "Details to come.",
        considerations: "Details to come.",
        timeToEntry: "TBC",
        salaryRange: "TBC",
        reflections: "Reflections to come.",
      },
      {
        title: "Solopreneur / Niche Business Owner",
        sector: "Self-directed",
        background: "Background to come.",
        summary:
          "Build something small, intentional, and entirely yours. Could be a product, service, or community around a specific passion or skill.",
        whyIt: "Radical autonomy; work shaped entirely around your strengths and values.",
        considerations: "Highest risk, highest reward. Requires financial runway and resilience.",
        timeToEntry: "6–24 months",
        salaryRange: "Variable — loss to £200k+",
        nextSteps: "Validate idea with 10 people, build an audience before building a product",
        reflections: "Reflections to come.",
      },
    ],
  },
};

export const planOrder = ["a", "b", "c"];
